### ISSUE TITLE
Finding Windows binaries broken after commit ad9c00d

### ISSUE THREAD

**Issue by rcassani** [ChristianGaser/cat12#21]
The file existence check added in ad9c00d breaks the finding of binaries on Windows.

As `findsubfiles()` in `cat_vol_findfiles.m` depends on the full filename (base + extension), but the check is just for the base.

https://github.com/ChristianGaser/cat12/blob/33278bc2c5361603870fa61d0fd9d9c3b87809d7/cat_vol_findfiles.m#L793

**Comment by ChristianGaser** [comment]
Update to r2560 which should solve that issue…

Christian

**Comment by rcassani** [comment]
@ChristianGaser thanks!
