### ISSUE TITLE
Mapping the brainstem nuclei

### ISSUE THREAD

**Issue by iPsych** [ChristianGaser/cat12#26]
Currently trying to extract the volumes of brainstem subnuclei (PAG, VTA, ... ) via custom template.
It seems that the whole brainstem is mapped to WM, 	as below.

cat_main_LAS.m
  % mapping of the brainstem to the WM (well there were some small GM
  % structures, but the should not effect the local segmentation to much.

and based on atlas .csv files, calculation of brainstem volume is also based on WM (0:1:0), 
[templates_MNI152NLin2009cAsym/lpba40.csv](https://github.com/ChristianGaser/cat12/blob/54257aee7be4ffdc4a98cdc4fe5d694f365780ee/templates_MNI152NLin2009cAsym/lpba40.csv#L54)
182;bBst;Bothside Brainstem;0;1;0;

If I run roi segmentation for brainstem nuclei volume using custom atlas in cat segmentation process,
Should I make ROIs 0:1:0 and get the value from WM (mwp2)?
The interesting part is if I put 1:1:0 and check both mwp1 and mwp2, both file has non-zero values, (mwp2 is greater than mwp1).

(i.e. PAG 0.4302 for mwp1 (GM), 0.8107 for mwp2 (WM) )

**Comment by robdahn** [comment]
1) cat_main_LAS: 
The LAS function is used to correct inhomogeneities and local intensity variations by optimising the tissue segments and using specific filters. For the brainstem we assume here that it mostly contain WM with small GM structures that are handled by using a maximum filter with size of 1 voxel. Moreover, the inhomogeneity maps are smoothed depending on the BCstr parameter (that can be controlled in the expert mode).  

2) ROIs:
The values are extracted from the specified tissue within the specified ROI if the flags are non-zero (and the atlas is specified in cat.extopts.atlas).
