### ISSUE TITLE
Issue with CAT12.9: Undefined function or variable 'cat_io_contains' in MATLAB 2021b

### ISSUE THREAD

**Issue by Zeus292** [ChristianGaser/cat12#30]
Hello,

I'm encountering an issue after installing CAT12.9 with MATLAB 2021b and the latest version of SPM12. When I try to launch CAT12, I receive the following error:
SPM12: spm_cat12 (vCAT12.9)                        12:27:17 - 02/09/2024
========================================================================

   _______  ___  _______    
  |  ____/ / _ \ \_   _/   
  | |___  / /_\ \  | |     Computational Anatomy Toolbox
  |____/ /_/   \_\ |_|     CAT12.9 - https://neuro-jena.github.io

 CAT default file:
	E:\study\matlab2021b\matlab\toolbox\spm12\toolbox\cat12\cat_defaults.m

Error using cat_vol_ctype (line 56)
Undefined function or variable 'cat_io_contains'.

Error in cat12>cat_interp_menuimgs (line 990)
for i=1:3, I2(:,:,i) = cat_vol_ctype(interp2(double(I(:,:,i)),X2,Y2)); end %#ok<AGROW>

Error in cat12>cat12_LayoutFcn (line 367)
  'cdata',cat_interp_menuimgs(cat_bg,tg),...

Error in cat12>gui_mainfcn (line 1139)
        gui_hFigure = feval(gui_State.gui_LayoutFcn, gui_SingletonOpt);

Error in cat12 (line 118)
    gui_mainfcn(gui_State, varargin{:});

Error in spm_cat12 (line 331)
cat12('fig');

Error in cat12 (line 62)
  spm_cat12;

Error in spm (line 954)
    evalin('base',xTB(i).prog);
 
Error while evaluating UIControl Callback.

Cannot access http://www.neuro.uni-jena.de/cat12/. Please check your proxy and/or firewall to allow access.
You can download your update at http://www.neuro.uni-jena.de/cat12/

It seems that the function cat_io_contains is missing or not recognized, which leads to the failure of initializing CAT12. Additionally, the CAT12 website is currently down, so I am unable to download or verify the latest files from there.
Is there a workaround for this issue, or has anyone else encountered this problem? Any guidance on how to resolve this would be greatly appreciated.

Thank you!

**Comment by robdahn** [comment]
Dear Zeus, 

sorry for the late reply, I assume you have already found out. If not, the servers are back up and the file is/was also here on Github.

Best regards 
R

**Comment by baimiaoshui** [comment]
I encountered the same problem, how was it finally solved?

**Comment by ChristianGaser** [comment]
cat_io_contains.m is included in CAT12.9, thus simply updating to the latest version (which is r2577 from May 2024) should solve the issue:
https://www.neuro.uni-jena.de/cat12/cat12_r2577.zip

Best,

Christian
